wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1636673121
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 3
      - 5
      - 9
      4: 3.8.10
      5: 0.12.6
      8:
      - 2
      - 5
